version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  flask_app:
    build:
      context: ./
    container_name: my_flask_app
    ports:
      - "8080:8080"


